import { User } from "../models/user.js";
import { randomChoice } from "../core/random.js";

const templates: Record<string, Record<string, string[]>> = {
  musician: {
    music: [
      "anyone else listening to {interest}?",
      "what do you guys think about {interest}?",
      "I've been listening to {interest} all day",
      "{interest} is seriously underrated",
      "just discovered {interest} and I'm hooked",
      "can we talk about how good {interest} is",
      "{interest} has been on repeat for me lately",
      "who else grew up on {interest}",
      "hot take: {interest} is better than people give it credit for",
      "{interest} live is a completely different experience",
      "putting {interest} on right now, perfect mood music",
      "does anyone have {interest} recommendations similar to this",
      "{interest} got me through some rough times ngl",
      "I never get tired of {interest}",
      "convince me {interest} isn't the best genre out there",
      "{interest} deserves way more recognition",
      "spent my whole paycheck on {interest} vinyl this month",
      "anyone going to any {interest} shows this year?",
      "{interest} really hits different at night",
      "just found an old {interest} album I forgot about",
      "what's your favorite {interest} album of all time",
      "{interest} is criminally underrated tbh",
      "been diving deep into {interest} history lately",
      "my playlist is 90% {interest} at this point",
      "{interest} production quality has gotten so good",
      "who are the best up and coming {interest} artists rn",
      "{interest} always brings back memories",
      "can't believe how underground {interest} still is",
      "{interest} changed the way I think about music",
      "just picked up a new instrument to play {interest}",
      "{interest} lyrics hit way too hard sometimes",
      "does anyone else analyze {interest} lyrics too much",
      "{interest} concerts are always worth the money",
      "trying to get into {interest}, where do I start",
      "{interest} is my go-to when I need to focus",
      "nothing beats a good {interest} session with friends",
      "{interest} scene has changed so much over the years",
      "just made a {interest} playlist for the road trip",
      "{interest} never fails to hype me up",
      "anyone else air drum to {interest}",
      "{interest} albums always tell a story",
      "found a rare {interest} record at a thrift store today",
      "{interest} is the soundtrack of my whole week",
      "who's your favorite {interest} producer",
      "{interest} sounds even better on vinyl",
      "just learned to play a {interest} song on guitar",
      "{interest} really is timeless music",
      "can we appreciate how talented {interest} musicians are",
      "{interest} always gets stuck in my head",
      "spent the whole night listening to {interest} deep cuts",
      "{interest} is criminally slept on by the mainstream",
    ],
  },

  shitposter: {
    memes: [
      "lol this is the funniest thing I've seen today",
      "why is this meme so accurate",
      "I can't stop laughing at this",
      "internet humor was better back then",
      "who made this, they deserve an award",
      "sending this to everyone I know",
      "this format never gets old",
      "I'm crying this is too real",
      "someone had way too much time on their hands for this",
      "this belongs in a museum",
      "not me screenshotting this immediately",
      "the accuracy of this is unreal",
      "bro I lost it at this",
      "this is unironically peak humor",
      "why did this hit so hard",
      "I've seen this 10 times and still laughing",
      "this needs to be studied academically",
      "whoever runs this account is a genius",
      "the internet is undefeated with this one",
      "screenshotting this for later",
      "this is the content I signed up for",
      "10/10 no notes",
      "certified classic right here",
      "this aged like fine wine",
      "I showed this to my whole group chat",
      "this is way too relatable",
      "not gonna lie I felt personally attacked",
      "this is comedy gold",
      "bookmarking this immediately",
      "the internet really cooked with this one",
      "this is peak comedic timing",
      "I'm sending this to literally everyone",
      "this deserves to go viral",
      "someone give this person an award",
      "this is exactly how I feel rn",
      "the caption really made this",
      "this is objectively hilarious",
      "why is nobody talking about this meme",
      "this format was already good but this is next level",
      "I've never related to something more",
      "this is going straight to my favorites",
      "the internet never disappoints",
      "this is what the internet was made for",
      "I can't believe how perfect this is",
      "certified banger meme right here",
      "this is unmatched energy",
      "nobody is topping this one",
      "this is the funniest thing all week",
      "I don't know why but this got me good",
      "this belongs in the hall of fame",
    ],

    gaming: [
      "this game is fucking ridiculous lol",
      "anyone else wasting their life playing this?",
      "I swear I'm addicted to this game",
      "just lost 5 hours to this without noticing",
      "this game lives rent free in my head",
      "why is this game so unreasonably good",
      "I can't stop thinking about this game",
      "put this game down for one second and it's already 3am",
      "this game ruined my sleep schedule",
      "anyone else's backlog just gathering dust because of this",
      "this game is a certified time thief",
      "I've rage quit this game so many times and still come back",
      "this game should come with a warning label",
      "just one more match turned into 4 hours",
      "this game has consumed my entire personality",
      "I need an intervention for how much I play this",
      "this game is unironically the best thing I've played this year",
      "who else is skipping responsibilities for this game",
      "this game has the most addictive gameplay loop ever",
      "I keep telling myself I'll stop after this match",
      "this game single handedly destroyed my productivity",
      "the grind in this game is actually insane",
      "I can't believe how much time I've sunk into this",
      "this game's community is chaotic and I love it",
      "just hit a new personal best in this game",
      "this game's updates always get me hyped",
      "anyone else building their whole schedule around this game",
      "this game has the best chaotic energy",
      "I've never rage quit and come back so fast",
      "this game is basically my second job at this point",
      "the amount of hours I've put into this is embarrassing",
      "this game is way too fun for its own good",
      "I keep losing track of time playing this",
      "this game just gets better the more I play",
      "who's still grinding this game with me",
      "this game's difficulty spikes are unforgiving",
      "just had the most chaotic match of my life",
      "this game has zero right being this fun",
      "I can't put this game down no matter how hard I try",
      "this game turned my weekend into a blur",
      "anyone else's friend group obsessed with this game too",
      "this game's mechanics are so satisfying",
      "I keep coming back to this game no matter what else I play",
      "this game deserves goty honestly",
      "just clutched the most insane play in this game",
      "this game is a rollercoaster of emotions",
      "I've never screamed at a screen this much",
      "this game's soundtrack alone is worth playing for",
      "who else has this game running in the background of their life",
      "this game is straight up chaotic evil and I love it",
    ],
  },

  lurker: {
    technology: [
      "does anyone know how this works?",
      "anyone else having this problem?",
      "I've been trying to figure this out",
      "is this normal or is something broken?",
      "anyone dealt with this issue before?",
      "not sure if this is a bug or intended",
      "does this happen to anyone else?",
      "trying to understand why this is happening",
      "is there a fix for this yet?",
      "anyone have any insight on this?",
      "spent hours trying to solve this",
      "this doesn't seem right, anyone know why?",
      "curious if this is a known issue",
      "still can't figure out what's causing this",
      "anyone found a workaround for this?",
      "is this expected behavior?",
      "not sure where to even start with this",
      "does anyone have documentation on this?",
      "this seems like it shouldn't be this complicated",
      "anyone else confused by this?",
      "trying to figure out the best approach here",
      "is there an official explanation for this?",
      "anyone run into this exact issue?",
      "not sure if I'm missing something obvious",
      "has this been reported anywhere?",
      "trying to see if this is just me",
      "anyone know a good resource to learn this?",
      "still trying to wrap my head around this",
      "is this a common issue?",
      "anyone tested this recently?",
      "not sure why this keeps happening",
      "does this look right to anyone else?",
      "trying to figure out what changed",
      "anyone have troubleshooting tips for this?",
      "is there a simpler way to do this?",
      "curious what's causing this behavior",
      "anyone else notice this got worse recently?",
      "trying to understand the root cause here",
      "not sure if this is worth reporting",
      "anyone know if this is being worked on?",
      "still stuck trying to figure this out",
      "does anyone have a step by step for this?",
      "is this just how it's supposed to work?",
      "anyone else lost on this one?",
      "trying to piece together what's going on",
      "not sure if this is hardware or software related",
      "anyone have experience with this specific issue?",
      "still can't tell if this is normal",
      "trying to see if anyone else replicated this",
      "is there somewhere better to ask about this?",
    ],
  },

  conspiracy: {
    conspiracy: [
      "there's definitely something weird going on here",
      "does anyone else think this isn't a coincidence?",
      "I've been looking into this for a while",
      "the timing on this is way too convenient",
      "nobody wants to talk about this for some reason",
      "connect the dots and it's pretty obvious",
      "this info was buried for a reason",
      "wake up, this is bigger than people think",
      "the official story doesn't add up at all",
      "why does nobody question this",
      "I did some digging and it's worse than I thought",
      "this has been happening for way longer than people realize",
      "follow the money and it all makes sense",
      "they don't want you looking into this",
      "the more I research this the less sense it makes",
      "something doesn't add up with the official explanation",
      "this is exactly what they don't want us discussing",
      "too many coincidences for this to be random",
      "the mainstream narrative is falling apart",
      "I've cross referenced this with a few sources and it checks out",
      "this got scrubbed from the internet almost immediately",
      "ask yourself why this isn't getting more coverage",
      "the pattern here is impossible to ignore",
      "this lines up with a lot of other stuff I've read",
      "nobody in power wants this getting out",
      "nothing about this feels like an accident",
      "nobody's asking the right questions about this",
      "nobody has been able to explain this to my satisfaction",
      "this contradicts everything we were told before",
      "you'd think this would be bigger news",
      "the more people look into this the more suspicious it gets",
      "this was hiding in plain sight the whole time",
      "who benefits from us not knowing this",
      "this info conveniently disappeared from search results",
      "there's a reason this doesn't get talked about",
      "history keeps repeating this exact pattern",
      "the details keep changing every time it's reported",
      "someone needs to be asking harder questions here",
      "this is way too coordinated to be a coincidence",
      "I've seen enough evidence to know something's off",
      "the silence around this speaks volumes",
      "this connects to way more than people realize",
      "it's wild how fast this got buried",
      "the dates on this line up in a suspicious way",
      "this is the tip of the iceberg honestly",
      "there's a reason certain people avoid this topic",
      "the amount of censorship around this is telling",
      "this deserves way more scrutiny than it's getting",
      "I trust my own research over the official line",
      "this pattern shows up way too often to ignore",
      "something about this has never sat right with me",
    ],

    paranormal: [
      "has anyone else experienced something like this?",
      "I don't think there's a normal explanation for this",
      "this happened to me and I still can't explain it",
      "does anyone else get weird feelings in places like this?",
      "I've heard so many stories similar to this one",
      "science can't explain everything, that's for sure",
      "this gave me chills reading it",
      "I believe there's more out there than we understand",
      "something similar happened to my family",
      "this is exactly the kind of thing that keeps me up at night",
      "I don't scare easy but this got to me",
      "there's always a rational explanation until there isn't",
      "this sounds exactly like something that happened to a friend of mine",
      "these stories never stop giving me goosebumps",
      "I've always felt like something was watching in old houses",
      "this is why I don't go looking for stuff like that alone",
      "there's too many accounts of this to just dismiss it",
      "something about old places always feels off to me",
      "I need to hear more about this experience",
      "this is the kind of thing that changes how you see the world",
      "nobody believed me when this happened to me either",
      "this matches up with stories from completely different places",
      "there's definitely more to this than meets the eye",
      "I've had experiences I still can't rationally explain",
      "this kind of stuff fascinates and terrifies me equally",
      "these encounters always seem to follow a pattern",
      "this is why I never go into abandoned buildings alone",
      "something about this story feels way too real",
      "I've read too many accounts like this to ignore it now",
      "this is exactly why I keep a light on at night",
      "there has to be something to all these consistent reports",
      "this reminds me of something my grandmother used to talk about",
      "I can't shake the feeling that this really happened",
      "these stories always have some detail that can't be explained away",
      "something about this account feels genuinely unsettling",
      "I've stopped trying to explain everything I've experienced",
      "this is the kind of story that sticks with you",
      "there's a reason these stories keep getting passed down",
      "I don't need proof, I just know what I felt",
      "this happened in a place I used to visit and it still bothers me",
      "these experiences are way more common than people admit",
      "something about the details here feels too specific to be made up",
      "I've talked to too many people with similar stories to doubt this",
      "this is exactly the kind of unexplainable stuff that fascinates me",
      "there's always that one story that changes how you sleep at night",
      "I can't explain what happened but I know it wasn't nothing",
      "this account gives me the same feeling as my own experience",
      "something about this just feels different from the usual stories",
      "I've never been able to shake off what happened to me",
      "this is the kind of thing you can't unhear once you know it",
    ],
  },
};

const genericTemplates: string[] = [
  "anyone interested in {topic}?",
  "does anyone here like {topic}?",
  "what's everyone's take on {topic}?",
  "getting into {topic} lately, anyone else?",
  "anyone know a lot about {topic}?",
  "just wanted to talk about {topic} for a sec",
  "is anyone else into {topic}?",
  "curious what people think about {topic}",
  "who else here is into {topic}",
  "been thinking about {topic} a lot lately",
  "anyone want to chat about {topic}?",
  "so is {topic} a thing people here are into?",
  "what got you all into {topic}?",
  "trying to find people who are into {topic} too",
  "anyone have good resources on {topic}?",
  "{topic} has been on my mind lately",
  "does this forum have a soft spot for {topic}?",
  "just started looking into {topic}, any tips?",
  "who's the resident {topic} expert here",
  "anyone else obsessed with {topic} right now?",
  "{topic} doesn't get talked about enough here",
  "feels like nobody talks about {topic} anymore",
  "what's the general opinion on {topic} around here?",
  "anyone want to nerd out about {topic} with me",
  "{topic} deserves its own thread honestly",
  "is there a good place to discuss {topic} here?",
  "randomly thinking about {topic}, anyone else into it?",
  "who's got recommendations related to {topic}?",
  "{topic} has taken over my free time lately",
  "anyone else spending way too much time on {topic}?",
  "what's something cool about {topic} people don't know?",
  "trying to get better at {topic}, any advice?",
  "does anyone else find {topic} really interesting?",
  "{topic} is kind of an underrated topic tbh",
  "who else lurks in {topic} threads but never posts",
  "just want to know if anyone shares my interest in {topic}",
  "what got everyone else into {topic}?",
  "{topic} conversations are always the best ones here",
  "anyone else feel like {topic} is underappreciated?",
  "looking to meet more people into {topic}",
  "so, {topic}. thoughts?",
  "{topic} thread, who's in?",
  "does this place have much of a {topic} community?",
  "always down to talk {topic} if anyone's interested",
  "anyone else check {topic} updates daily?",
  "what's the deal with {topic} lately",
  "{topic} rabbit hole, anyone else fallen in",
  "just here to see if anyone else is into {topic}",
  "who wants to swap {topic} recommendations",
  "{topic} is criminally underdiscussed on here",
  "anyone else think {topic} deserves more attention?",
];

export function generatePostContent(user: User, topic: string): string {
  const archetypeTemplates = templates[user.archetype];
  const topicTemplates = archetypeTemplates?.[topic];

  const pool = topicTemplates ?? genericTemplates;
  const template = randomChoice(pool);

  const interest = randomChoice(user.interests);

  return template.replace("{interest}", interest).replace("{topic}", topic);
}
